### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [dev-benjy/ultimatexylophone#1]
Hello, <br/> <br/>I'm the creator of the Nice Vibrations asset, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. <br/>After that delay Github will take that repo down. <br/> <br/>Thanks, <br/>Renaud

**Comment by dev-benjy** [comment]
Hi,I am so sorry your package was published with my project. I sincerely apologise as I had forgotten that I used it in this project. It will be removed within the next 12 hrs.I hope you accept this sincere apology.Benjamin JohnDigital-MarketingVigilance 24X7​ ---- On Fri, 11 Jun 2021 06:11:27 +0530  ***@***.***  wrote ----
Hello,  I'm the creator of the Nice Vibrations asset, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. After that delay Github will take that repo down.  Thanks, Renaud

**Comment by dev-benjy** [comment]
The package has been removed.
